### ISSUE TITLE
Possible to train 7B llama model with training/run.py?

### ISSUE THREAD

**Issue by 152334H** [Dao-AILab/flash-attention#474]
Hi, I saw the [amazing efficiency results](https://github.com/Dao-AILab/flash-attention/tree/main/training) in the training directory, and wanted to see if pretraining a Llama-7B equivalent would work on the repo.

From my understanding of [llama.py](https://github.com/Dao-AILab/flash-attention/blob/main/flash_attn/models/llama.py#L340), there is some equivalency between llama models, and specific configurations of `flash_attn.models.gpt.GPTLMHeadModel`. So I tried to create a `training/configs/models/llama.yaml` config based on that (for 7B):

```
defaults:
  - _self_

_target_: flash_attn.models.gpt.GPTLMHeadModel
_recursive_: True
config:
  _target_: transformers.GPT2Config
  #n_positions: ${datamodule.max_length}
  activation_function: swiglu
  attn_pdrop: 0.0
  bos_token_id: 1
  embd_pdrop: 0.0
  eos_token_id: 2
  initializer_range: 0.02
  layer_norm_epsilon: 1e-05
  mlp_fc1_bias: false
  mlp_fc2_bias: false
  model_type: gpt2
  n_embd: 4096
  n_head: 32
  n_inner: 11008
  n_layer: 32
  n_positions: 0
  out_proj_bias: false
  pad_token_id: 0
  qkv_proj_bias: false
  reorder_and_upcast_attn: false
  resid_pdrop: 0.0
  rms_norm: true
  rotary_emb_fraction: 1.0
  rotary_emb_interleaved: true
  scale_attn_by_inverse_layer_idx: false
  scale_attn_weights: true
  summary_activation: null
  summary_first_dropout: 0.1
  summary_proj_to_labels: true
  summary_type: cls_index
  summary_use_proj: true
  tie_word_embeddings: false
  transformers_version: 4.31.0
  use_cache: false
  vocab_size: 32000
```

As well as an OpenWebText experiment config for training,

```yaml
# @package _global_
defaults:
  - /experiment/owt/base.yaml
  - override /model: llama
  - override /optimizer: adamw-apex-zero

model:
  config:
    residual_in_fp32: True
    use_flash_attn: True
    mlp_checkpoint_lvl: 1

datamodule:
  batch_size: 1 # use smallest possible bs

trainer:
  strategy:
    _target_: src.utils.ddp_zero2.DDPStrategyZero2
    find_unused_parameters: False
    gradient_as_bucket_view: True
```

However, despite enabling what (seems to be) Zero2, running the trainer on 8xA100-40GB still appears to run out of memory:

```bash
$ HYDRA_FULL_ERROR=1 python run.py experiment=owt/llama trainer.devices=8 
... (omitted) ...
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 25.10 GiB. GPU 0 has a total capacty of 39.39 GiB of which 13.04 GiB is free. Including non-PyTorch memory, this process has 26.34 GiB memory in use. Of the allocated memory 25.10 GiB is allocated by PyTorch, and 982.50 KiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

This seems weird to me, considering other trainers (such as lit-llama or megatron-deepspeed, or even HF based ones like axolotl) are able to fit 7B models on a 8xA100 nodes.

Am I failing to enable ZeRO properly? Or missing some other memory saving approaches?
